
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ "frontend" }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ "frontend" }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }} 
type: ClusterIP
