
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ "frontend" }}
spec:
  replicas: {{ .Values.frontendService.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ "frontend" }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ "frontend" }}
    spec:
      containers:
        - name: {{ "frontend" }}
          image: {{ .Values.frontendService.image }}
          ports:
            - containerPort: {{ .Values.frontendService.port }}
