
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ "user" }}
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ "user" }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ "user" }}
    spec:
      containers:
        - name: {{ "user" }}
          image: {{ .Values.userService.image }}
          ports:
            - containerPort: {{ .Values.userService.port }}
