
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ "user" }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ "user" }}
  ports:
    - protocol: TCP
      port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
  type: ClusterIP
